#!/usr/bin/python3

import sys

def cribar(n):
    l = list(range(2, n + 1))
    for i in l:
         for j in l:
             if j % i == 0 and j != i:
                 del l[l.index(j)]
    return l

t = int(input().strip())
for a in range(t):
    n = int(input().strip())
    primo = 1
    ar = 0
    l = []
    if n % 10 == 0 or n % 5 == 0:
        n = 1
        primo = 5
    while(1):
        if n == 1:
            break
        l = cribar(a)
        if n % l[ar] == 0:
            n = int(n / l[ar])
            if l[ar] > primo:
                primo = l[ar]
        else:
            ar += 1
    print(primo)
